// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"

	"github.com/google/uuid"
)

type Assignment struct {
	UserID   uuid.UUID `json:"user_id"`
	AuditID  uuid.UUID `json:"audit_id"`
	SectorID string    `json:"sector_id"`
}

type Audit struct {
	ID        uuid.UUID `json:"id"`
	Title     string    `json:"title"`
	Norm      string    `json:"norm"`
	Status    string    `json:"status"`
	CreatedAt time.Time `json:"created_at"`
}

type User struct {
	ID       uuid.UUID `json:"id"`
	Email    string    `json:"email"`
	Password string    `json:"password"`
	Role     string    `json:"role"`
}
