// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const assignUserToAudit = `-- name: AssignUserToAudit :exec
INSERT INTO assignments (user_id, audit_id, sector_id)
VALUES ($1, $2, $3)
`

type AssignUserToAuditParams struct {
	UserID   uuid.UUID `json:"user_id"`
	AuditID  uuid.UUID `json:"audit_id"`
	SectorID string    `json:"sector_id"`
}

func (q *Queries) AssignUserToAudit(ctx context.Context, arg AssignUserToAuditParams) error {
	_, err := q.db.ExecContext(ctx, assignUserToAudit, arg.UserID, arg.AuditID, arg.SectorID)
	return err
}

const createAudit = `-- name: CreateAudit :one
INSERT INTO audits (id, title, norm, status, created_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, title, norm, status, created_at
`

type CreateAuditParams struct {
	ID        uuid.UUID `json:"id"`
	Title     string    `json:"title"`
	Norm      string    `json:"norm"`
	Status    string    `json:"status"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) CreateAudit(ctx context.Context, arg CreateAuditParams) (Audit, error) {
	row := q.db.QueryRowContext(ctx, createAudit,
		arg.ID,
		arg.Title,
		arg.Norm,
		arg.Status,
		arg.CreatedAt,
	)
	var i Audit
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Norm,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getAuditByID = `-- name: GetAuditByID :one
SELECT id, title, norm, status, created_at FROM audits
WHERE id = $1
`

func (q *Queries) GetAuditByID(ctx context.Context, id uuid.UUID) (Audit, error) {
	row := q.db.QueryRowContext(ctx, getAuditByID, id)
	var i Audit
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Norm,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getAuditsByUserID = `-- name: GetAuditsByUserID :many
SELECT a.id, a.title, a.norm, a.status, a.created_at FROM audits a
JOIN assignments asg ON a.id = asg.audit_id
WHERE asg.user_id = $1
`

func (q *Queries) GetAuditsByUserID(ctx context.Context, userID uuid.UUID) ([]Audit, error) {
	rows, err := q.db.QueryContext(ctx, getAuditsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Audit
	for rows.Next() {
		var i Audit
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Norm,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
